# version: "3"
# services:
#   django:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 8000:8000
#     depends_on:
#       - mysql

#   mysql:
#     image: mysql:latest
#     environment:
#       - MYSQL_ROOT_PASSWORD=''
#       - MYSQL_DATABASE=shoponline
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=''


version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python 3.8 manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: sqlite3:latest
    environment:
      - SQLITE3_DB = db.sqlite3

